name: gemographyMobileChallenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  provider: ^4.3.2+2
  cached_network_image: ^2.3.2+1
  date_format: ^1.0.9
  hexcolor: ^1.0.4
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  toggle_switch: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
